name: DockerTestServer
on: 
  workflow_dispatch:
jobs:
  Download:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash

    steps:
      - name: List files before
        run: pwd
      - name: Set working directory
        working-directory: ./keys
      - run: pwd
      - run: touch 1.txt
      - name: Your other steps here
        run: |
          # Your commands here
      - name: List files after
        run: ls -l
      - run: cd /
      - run: ls -l
      - run: sudo snap install tree 
      - run: tree /home/runner/work/TerraformAws/TerraformAws
# name: DockerTestServer
# on: 
#   workflow_dispatch:
# jobs:
#   Download:
#     runs-on: ubuntu-latest
#     defaults:
#         run:
#           shell: bash
#           working-directory: .
        
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECREY_KEY }}
#     steps:
#         - name: Get code
#           uses: actions/checkout@v3
        
#         - name: Setup Terraform
#           uses: hashicorp/setup-terraform@v2
#           with:
#             terraform_version: 1.5.6

#         - name: Init Terraform
#           run: terraform init
          
#         - name: Terraform plan
#           run: terraform plan
          
#         - name: Apply Terraform
#           run: terraform apply -auto-approve
#         # Add a 3-minute delay before destroying resources
#         - name: Delay
#           run: sleep 180 
#         - name: Destroy Terraform Resources
#           run: terraform destroy -auto-approve
