name: DockerTestServer
on: 
  workflow_dispatch:
jobs:
  Download:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: .
    steps:
        - name: Get code
          uses: actions/checkout@v3
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.5.6
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        - name: Init Terraform
          run: terraform init
        - name: Terraform plan
          run: terraform plan
        - name: Apply Terraform
          run: terraform apply -auto-approve
        # Add a 3-minute delay before destroying resources
        - name: Delay
          run: sleep 180 
        - name: Destroy Terraform Resources
          run: terraform destroy -auto-approve