name: DockerTestServer
on: 
  workflow_dispatch:
jobs:
  Download:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: .
    steps:
        - name: Get code
          uses: actions/checkout@v3
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.5.6
            
        - name: Configure AWS credentials
          run: |
            export access="${{ secrets.AWS_ACCESS_KEY }}" 
            export secret="${{ secrets.AWS_SECREY_KEY }}" 
            export AWS_ACCESS_KEY_ID="$access"
            export AWS_SECRET_ACCESS_KEY="$secret"
            echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
            terraform init
        - name: Init Terraform
          run: terraform init
          
        - name: Terraform plan
          run: terraform plan
          
        - name: Apply Terraform
          run: terraform apply -auto-approve
        # Add a 3-minute delay before destroying resources
        - name: Delay
          run: sleep 180 
        - name: Destroy Terraform Resources
          run: terraform destroy -auto-approve
